//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.02 at 06:08:56 PM CET 
//


package deep.util.pojo;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="person" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="c" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="cn" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="employeenumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ikeahrid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="facsimiletelephonenumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="givenname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="sn" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ikeacostcenter" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ikeadepartment" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ikeahomesite" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ikealangcode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ikealegacyuid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ikearolelist">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="initials" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="l" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="mail" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="manager" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="mobile" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ou" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="telephonenumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="uid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ikeastatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ikeaguid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ikeabusinessunit" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="createtimestamp" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="modifytimestamp" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="object" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="generated" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "person"
})
@XmlRootElement(name = "cdsexport")
public class Cdsexport {

    protected List<Person> person;
    @XmlAttribute(name = "object")
    protected String object;
    @XmlAttribute(name = "type")
    protected String type;
    @XmlAttribute(name = "generated")
    protected String generated;

    /**
     * Gets the value of the person property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the person property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPerson().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Person }
     * 
     * 
     */
    public List<Person> getPerson() {
        if (person == null) {
            person = new ArrayList<Person>();
        }
        return this.person;
    }

    /**
     * Gets the value of the object property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObject() {
        return object;
    }

    /**
     * Sets the value of the object property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObject(String value) {
        this.object = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the generated property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGenerated() {
        return generated;
    }

    /**
     * Sets the value of the generated property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGenerated(String value) {
        this.generated = value;
    }





}
